### ISSUE TITLE
请求中带有查询参数不会带到转发请求中吗？

### ISSUE THREAD

**Issue by Asher-Tan** [huanz/gulp-devserver#1]
比如http://192.168.11.109:3000/admin/service?&page=1&start=0&limit=25  转发到 http://192.168.11.109:8090/admin/service?&page=1&start=0&limit=25中可以吗？试了带了参数就404了，找不到路径

**Comment by huanz** [comment]
@Asher-Tan Thanks for feedback. fixed, please update your version to the latest
