### ISSUE TITLE
最新的0.6.2版本，post类型请求接口，如果带参数，请求会一直处于pending状态

### ISSUE THREAD

**Issue by zhangtian** [huanz/gulp-devserver#5]
如上，不带参数没问题。
麻烦有空看下吧，多谢啦

**Comment by huanz** [comment]
@zhangtian 可否贴下你的代码？我测试下

**Comment by zhangtian** [comment]
gulp.task('devserver', () => {
  gulp.src(['./'])
    .pipe(server({
      port: '8082',
      open: false,
      livereload: {
        // clientConsole: true
      },
      proxy: {
        enable: true,
        host: 'https://www.yooli.com/',
        urls: new RegExp('^\/(abc)')
      }
    }))
})

ajax请求：
$.post('/abc/1', {a: 1}, function(data){

})

就是正常配置的

**Comment by huanz** [comment]
@zhangtian 试试新版

**Comment by zhangtian** [comment]
0.6.2版本不是最新版么？
新版怎么弄
@huanz

**Comment by huanz** [comment]
@zhangtian 0.6.3

**Comment by zhangtian** [comment]
可以的。忘了回复了！ @huanz 谢谢
